# Generated by Django 4.0.4 on 2022-05-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0002_about_color_contactus_serviceapi_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantite', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(blank=True, choices=[('T-chirt', 'T-chirt'), ('Hodie', 'Hodie'), ('Sweat', 'Sweat'), ('vetement de travail', 'vetement de travail')], max_length=200, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('designs', models.ImageField(blank=True, null=True, upload_to='upload_path')),
                ('ispayed', models.BooleanField(default=False)),
                ('accepeted', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('size', models.ManyToManyField(blank=True, null=True, related_name='sizeee', to='Ecomerceprintpruduct.size')),
            ],
        ),
    ]
