# Generated by Django 4.0.4 on 2022-05-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0002_about_contactus_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Serviceapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('info', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
