# Generated by Django 4.0.4 on 2022-05-31 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uplodedebydesigner',
        ),
    ]
