# Generated by Django 4.0.4 on 2022-05-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0003_designs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serviceapi',
            new_name='Service',
        ),
    ]
