# Generated by Django 4.0.4 on 2022-05-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0004_rename_serviceapi_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designs',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
