# Generated by Django 4.0.4 on 2022-05-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0004_remove_product_uplodedebydesigner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/image/logotab3lia.png', null=True, upload_to='image/'),
        ),
    ]
