# Generated by Django 4.0.4 on 2022-05-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0005_alter_designs_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designs',
            name='category',
            field=models.CharField(blank=True, choices=[('T-chirt', 'T-chirt'), ('Hodie', 'Hodie'), ('Sweat', 'Sweat'), ('pulls', 'pulls')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('T-chirt', 'T-chirt'), ('Hodie', 'Hodie'), ('pulls', 'pulls')], max_length=200, null=True),
        ),
    ]
