# Generated by Django 4.0.4 on 2022-05-31 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecomerceprintpruduct', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uplodedebydesigner',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Designs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantite', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(blank=True, choices=[('T-shirt', 'T-shirt'), ('Sweat', 'Sweat'), ('pulls', 'pulls')], max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('designs', models.ImageField(blank=True, null=True, upload_to='upload_path')),
                ('ispayed', models.BooleanField(default=False)),
                ('accepeted', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('uplodedebyclient', models.BooleanField(default=True)),
                ('size', models.ManyToManyField(blank=True, null=True, related_name='sizeee', to='Ecomerceprintpruduct.size')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
