# Generated by Django 4.0.4 on 2022-05-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='logotab3lia.png', null=True, upload_to='image/'),
        ),
    ]
