# Generated by Django 4.0.4 on 2022-05-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0007_order_shippingaddress_review_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
