# Generated by Django 4.0.4 on 2022-05-20 15:20

import Ecomerceprintpruduct.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0007_product_color_product_instock_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('T-chirt', 'T-chirt'), ('Hodie', 'Hodie'), ('gacket', 'gacket')], max_length=200, null=True, verbose_name=Ecomerceprintpruduct.models.Category),
        ),
    ]
