# Generated by Django 4.0.4 on 2022-05-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0008_designs_createdat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.AddField(
            model_name='designs',
            name='uplodedebyclient',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='uplodedebydesigner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slides',
            name='backgrounds',
            field=models.CharField(blank=True, default='bg-[#78cbc0]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slides',
            name='contectHeader',
            field=models.TextField(blank=True, default="Ajoutez une appli d'impression à la demande à votre boutique en ligne", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slides',
            name='contectParagraphe',
            field=models.TextField(blank=True, default='Upto 40%/ off', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slides',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slides',
            name='src',
            field=models.ImageField(blank=True, default='/imageslide/logotab3lia.png', null=True, upload_to='imageslide/'),
        ),
    ]
