# Generated by Django 4.0.4 on 2022-05-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0010_designs_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='designsmodel',
        ),
    ]
