# Generated by Django 4.0.4 on 2022-05-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0011_rename_image_product_designsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='designsmodel',
            new_name='image',
        ),
    ]
