# Generated by Django 4.0.4 on 2022-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(choices=[('black', 'black'), ('white', 'white')], null=True, to='Ecomerceprintpruduct.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], null=True, to='Ecomerceprintpruduct.size'),
        ),
    ]
