# Generated by Django 4.0.4 on 2022-05-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0014_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(choices=[('black', 'black'), ('white', 'white')], default=1, null=True, to='Ecomerceprintpruduct.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default=1, null=True, to='Ecomerceprintpruduct.size'),
        ),
    ]
