# Generated by Django 4.0.4 on 2022-05-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0015_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL')], default=1, null=True, to='Ecomerceprintpruduct.size'),
        ),
    ]
