# Generated by Django 4.0.4 on 2022-05-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0016_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(choices=[(1, 'black'), (2, 'white')], default=1, null=True, to='Ecomerceprintpruduct.color'),
        ),
    ]
