# Generated by Django 4.0.4 on 2022-05-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0019_alter_color_color_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(choices=[(1, 'black'), (2, 'white')], null=True, to='Ecomerceprintpruduct.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL')], null=True, to='Ecomerceprintpruduct.size'),
        ),
    ]
