# Generated by Django 4.0.4 on 2022-05-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0020_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(choices=[('black', 'black'), ('white', 'white')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecomerceprintpruduct.color'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecomerceprintpruduct.size'),
        ),
    ]
