# Generated by Django 4.0.4 on 2022-05-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0021_remove_product_color_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(choices=[(1, 'black'), (2, 'white')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecomerceprintpruduct.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecomerceprintpruduct.size'),
        ),
    ]
