# Generated by Django 4.0.4 on 2022-05-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerceprintpruduct', '0029_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(1, 'T-chirt'), (2, 'Hodie'), (3, 'gacket')], max_length=50),
        ),
    ]
